apiVersion: v1
kind: Service
metadata:
  name: {{ include "librespeed.fullname" . }}
  labels:
    {{- include "librespeed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: librespeed
      protocol: TCP
      name: librespeed
  selector:
    {{- include "librespeed.selectorLabels" . | nindent 4 }}
