version: 2.1

jobs:
  helm:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "eb:20:a3:f7:55:3d:d5:83:fb:12:ee:40:ac:2f:80:26"
      - run: 
          name: "Install Dependencies"
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run:
          name: "Helm lint"
          command: "helm lint helm-charts/*"
      - run:
          name: "Helm Package"
          command: "helm package helm-charts/*"
      - run:
          name: "Helm repo index"
          command: "helm repo index --url https://maxxblow.de/helm-charts/ ."
      - run:
          name: "Git config"
          command: |
            git config user.email "0hlov3@protonmail.com" && \
            git config user.name "CircleCI"
      - run:
          name: "Git add"
          command: "git add ."
      - run:
          name: "Git commit"
          command: "git commit -m '[skip ci] Updates Helm Charts from CircleCI'"
      - run:
          name: "git push"
          command: "git push"         

workflows:
  helm-workflow:
    jobs:
      - helm:
          filters:
                branches:
                  only:
                    - main