apiVersion: v1
kind: Service
metadata:
  name: {{ include "writefreely.fullname" . }}
  labels:
    {{- include "writefreely.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: writefreely
      protocol: TCP
      name: writefreely
  selector:
    {{- include "writefreely.selectorLabels" . | nindent 4 }}
