apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinafore.fullname" . }}
  labels:
    {{- include "pinafore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pinafore
      protocol: TCP
      name: pinafore
  selector:
    {{- include "pinafore.selectorLabels" . | nindent 4 }}
