apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotosocial.fullname" . }}
data:
  config.yaml: |    
    ###########################
    ##### GENERAL CONFIG ######
    ###########################
    log-level: {{ .Values.gotosocial.config.logLevel | default "info" }}
    log-db-queries: {{ .Values.gotosocial.config.logDBQueries | default false }}
    application-name: {{ .Values.gotosocial.config.applicationName | default "gotosocial" }}
    host: {{ .Values.gotosocial.config.host }}
    account-domain: {{ .Values.gotosocial.config.accountDomain }}
    protocol: {{ .Values.gotosocial.config.protocol | default "https" }}
    bind-address: {{ .Values.gotosocial.config.protocol | default "0.0.0.0" }}
    port: {{ .Values.service.port | default 8080}}
    trusted-proxies:
      - "127.0.0.1/32"
    {{- if .Values.gotosocial.config.trustedProxies -}}
      {{ .Values.gotosocial.config.trustedProxies | toYaml | nindent 6 }}
    {{- end }}
    #{{- if eq .Values.gotosocial.config.db.type "sqlite" }}
    #############################
    ###### DATABASE CONFIG ######
    #############################
    #db-type: {{ .Values.gotosocial.config.db.type | default "sqlite" }}
    #db-address: {{ .Values.gotosocial.config.db.address | default "/gotosocial/storage/sqlite.db" }} 
    #db-user: {{ .Values.gotosocial.config.db.user | default "gotosocial" }}
    #db-password: {{ .Values.gotosocial.config.db.password }}
    #db-database: {{ .Values.gotosocial.config.db.database | default "gotosocial" }}
    #db-tls-mode: {{ .Values.gotosocial.config.db.tlsMode | default "disable" }}
    #db-tls-ca-cert: {{ .Values.gotosocial.config.db.tlsCaCert | default "" }}
    #{{- end }}
    ######################
    ##### WEB CONFIG #####
    ######################
    web-template-base-dir: {{ .Values.gotosocial.config.web.templateBaseDir | default "./web/template/" }}
    web-asset-base-dir: {{ .Values.gotosocial.config.web.assetBaseDir | default "./web/assets/" }}
    ###########################
    ##### ACCOUNTS CONFIG #####
    ###########################
    accounts-registration-open:  {{ .Values.gotosocial.config.accounts.registrationOpen | default true }}
    accounts-approval-required:  {{ .Values.gotosocial.config.accounts.approvalRequired | default true }}
    accounts-reason-required:  {{ .Values.gotosocial.config.accounts.reasonRequired | default true }}
    ########################
    ##### MEDIA CONFIG #####
    ########################
    media-image-max-size: {{ .Values.gotosocial.config.media.imageMaxSize | default 2097152 }}
    media-video-max-size: {{ .Values.gotosocial.config.media.videoMaxSize | default 10485760 }}
    media-description-min-chars: {{ .Values.gotosocial.config.media.descriptionMinChars | default 0 }}
    media-description-max-chars: {{ .Values.gotosocial.config.media.descriptionMaxChars | default 500 }}
    media-remote-cache-days: {{ .Values.gotosocial.config.media.descriptionMaxChars | default 30 }}
    ##########################
    ##### STORAGE CONFIG #####
    ##########################
    storage-backend: {{ .Values.gotosocial.config.media.descriptionMaxChars | default "local" }}
    storage-local-base-path: "/gotosocial/storage"
    ###########################
    ##### STATUSES CONFIG #####
    ###########################
    statuses-max-chars: {{ .Values.gotosocial.config.statuses.maxChars | default 5000 }}
    statuses-cw-max-chars: {{ .Values.gotosocial.config.statuses.cwMaxChars | default 100 }}
    statuses-poll-max-options: {{ .Values.gotosocial.config.statuses.pollMaxOptions | default 6 }}
    statuses-poll-option-max-chars: {{ .Values.gotosocial.config.statuses.pollOptionMaxChars | default 50 }}
    statuses-media-max-files: {{ .Values.gotosocial.config.statuses.mediaMaxFiles | default 6 }}
    ##############################
    ##### LETSENCRYPT CONFIG #####
    ##############################
    letsencrypt-enabled: {{ .Values.gotosocial.config.letsencrypt.enabled | default false }}
    letsencrypt-port: {{ .Values.gotosocial.config.letsencrypt.port | default 80 }}
    letsencrypt-cert-dir: {{ .Values.gotosocial.config.letsencrypt.certDir | default "/gotosocial/storage/certs" }}
    letsencrypt-email-address: {{ .Values.gotosocial.config.letsencrypt.emailAddress | default "" }}
    #######################
    ##### OIDC CONFIG #####
    #######################
    oidc-enabled: {{ .Values.gotosocial.config.oidc.enabled | default false }}
    oidc-idp-name: {{ .Values.gotosocial.config.oidc.idpName | default "" }}
    oidc-skip-verification: {{ .Values.gotosocial.config.oidc.skipVerification | default false }}
    oidc-issuer: {{ .Values.gotosocial.config.oidc.issuer | default "" }}
    oidc-client-id: {{ .Values.gotosocial.config.oidc.clientID | default "" }}
    oidc-client-secret: {{ .Values.gotosocial.config.oidc.clientSecret | default "" }}
    oidc-scopes:
    {{- if .Values.gotosocial.config.oidc.oidcScopes -}}
      {{ .Values.gotosocial.config.oidc.oidcScopes | toYaml | nindent 6 }}
    {{- end }}
    #######################
    ##### SMTP CONFIG #####
    #######################
    smtp-host: {{ .Values.gotosocial.config.smtp.host | default "" }}
    smtp-port: {{ .Values.gotosocial.config.smtp.port | default 0 }}
    smtp-username: {{ .Values.gotosocial.config.smtp.userName | default "" }}
    smtp-password: {{ .Values.gotosocial.config.smtp.password | default "" }}
    smtp-from: {{ .Values.gotosocial.config.smtp.from | default "" }}
    #########################
    ##### SYSLOG CONFIG #####
    #########################
    syslog-enabled: {{ .Values.gotosocial.config.syslog.enabled | default false }}
    syslog-protocol: {{ .Values.gotosocial.config.syslog.protocol | default "udp" }}
    syslog-address: {{ .Values.gotosocial.config.syslog.address | default "localhost:514" }}