apiVersion: v1
kind: Service
metadata:
  name: {{ include "privatebin.fullname" . }}
  labels:
    {{- include "privatebin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: privatebin
      protocol: TCP
      name: privatebin
  selector:
    {{- include "privatebin.selectorLabels" . | nindent 4 }}
