---
apiVersion: v2
name: vector-element
description: |
  Element (formerly known as Vector and Riot) is a Matrix web client built using the Matrix React SDK.
icon: https://element.io/images/element-logo.svg
home: https://github.com/0hlov3/helm-charts/helm-charts/vector-element
#ChartVersion
version: 0.1.1
# MatrixVersion
appVersion: v1.10.10
type: application

maintainers:
  - name: 0hlov3
    email: 0hlov3@protonmail.com
    url: https://schoenwald.me